baseURL: "http://example.org/"
languageCode: en-us
title: Karthik Narasimhan's Lab
theme: lab-website-theme
favicon: favicon.ico
params:
  mode: toggle # dark mode - {toggle, auto, dark, light}
  social:
    - name: GitHub
      icon: github
      url: https://github.com/princeton-nlp
  authors:
    # Faculty
    karthikn:
      name: Karthik Narasimhan
      title: Assistant Professor
      pic: karthikn.jpeg
      link: https://www.cs.princeton.edu/~karthikn/
      github: karthikncode
      scholar: https://scholar.google.com/citations?user=euc0GX4AAAAJ
      twitter: karthik_r_n
      interests: "Embodied Language Understanding, Language Guided ML, Representation Learning, RL Safety"
    danqic:
      name: Danqi Chen
      title: Assistant Professor
      pic: danqi.jpeg
      link: https://www.cs.princeton.edu/~danqic/
    sarora:
      name: Sanjeev Arora
      title: Professor
      pic: sanjeev.jpeg
      link: https://www.cs.princeton.edu/~arora/
    olgarus:
      name: Olga Russakovsky
      title: Assistant Professor
      pic: https://www.cs.princeton.edu/~olgarus/photos/OlgaRussakovsky.JPG
      link: https://www.cs.princeton.edu/~olgarus/
    anirudhm:
      name: Anirudha Majumdar
      title: Assistant Professor
      pic: https://mae.princeton.edu/sites/default/files/Majumdar-min_1.jpg
      link: https://mae.princeton.edu/people/faculty/majumdar
    chuangg:
      name: Chuang Gan
      title: Assistant Professor
      pic: https://people.csail.mit.edu/ganchuang/imgs/portrait.jpg
      link: https://people.csail.mit.edu/ganchuang/ch
    joshuat:
      name: Joshua Tenenbaum
      title: Professor
      pic: https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZcUwgGbxnoHdQMOqn66N8Q3QvURo2LGc5T-Pn9J2LbUaaoe3p
      link: http://web.mit.edu/cocosci/josh.html
    ramadge:
      name: Peter Ramadge
      title: Professor
      pic: https://ece.princeton.edu/sites/g/files/toruqf1836/files/styles/3x4_750w_1000h/public/ramadge-p.jpg?itok=Md1sQ0if
      link: https://ece.princeton.edu/people/peter-j-ramadge
    lukez:
      name: Luke Zettlemoyer
      title: Professor
      pic: https://s3-us-west-2.amazonaws.com/www-cse-public/images/portraits/lsz_sm.jpg
      link: https://www.cs.washington.edu/people/faculty/lsz
    christosp:
      name: Christos Papadimitriou
      title: Professor
      pic: https://ieeecs-media.computer.org/wp-media/2022/02/25182218/christos.jpg
      link: https://www.engineering.columbia.edu/faculty/christos-papadimitriou
    thomasg:
      name: Thomas L. Griffiths
      title: Professor
      pic: https://cocosci.princeton.edu/tom/griffiths_0_0.jpg
      link: https://psych.princeton.edu/person/tom-griffiths
    markb:
      name: Mark Braverman
      title: Professor
      pic: https://mbraverm.princeton.edu/media/Braverman-2019-small.jpg#float-left
      link: https://mbraverm.princeton.edu/
    shamk:
      name: Sham Kakade
      title: Professor
      pic: https://projects.iq.harvard.edu/files/styles/os_files_xxlarge/public/kakade/files/img-kakade_0.jpg?m=1633542504&itok=6G9MOC5l
      link: https://sham.seas.harvard.edu/
    andrewl:
      name: Andrew S. Lan
      title: Assistant Professor
      pic: https://people.umass.edu/~andrewlan/pic/lan.jpeg
      link: https://people.umass.edu/~andrewlan/
    nathand:
      name: Nathaniel D. Daw
      title: Professor
      pic: https://www.princeton.edu/~ndaw/me2.jpg
      link: https://www.princeton.edu/~ndaw/
    jonathanc:
      name: Jonathan D. Cohen
      title: Professor
      pic: https://pni.princeton.edu/sites/default/files/styles/people_directory/public/images/faculty-details/johnathan-cohen.jpg?itok=qDU9onfw
      link: https://pni.princeton.edu/faculty/jonathan-cohen

    # Current Students
    carlosej:
      name: Carlos E. Jimenez
      title: PhD Student
      pic: carlosej.jpeg
      link: http://www.carlosejimenez.com/
      github: carlosejimenez
      scholar: https://scholar.google.com/citations?user=Ue4wghAAAAAJ
      twitter: _carlosejimenez
      interests: "Efficient Pre-Training, Code Generation, Semantic Parsing, Program Synthesis"
    jy1682:
      name: John Yang
      title: MSE Student
      pic: jy1682.jpg
      link: https://john-b-yang.github.io
      github: john-b-yang
      scholar: https://scholar.google.com/citations?user=71G11ksAAAAJ
      twitter: jyangballin
      interests: "Language Interaction, Multimodal Learning, Neurosymbolic Programs"
    asd:
      name: Ameet Deshpande
      title: PhD Student
      pic: asd.jpg
      link: https://ameet-1997.github.io/
      github: ameet-1997
      scholar: https://scholar.google.co.in/citations?user=332L1coAAAAJ
      twitter: AmeetDeshpande_
      interests: ""
    hjwang:
      name: Austin H. Wang
      title: PhD Student
      pic: hjwang.png
      twitter: awhanjie
      link: https://ahjwang.github.io/
      github: ahjwang
      scholar: https://scholar.google.com/citations?user=BB4R2_gAAAAJ
      interests: ""
    jtuyls:
      name: Jens Tuyls
      title: PhD Student
      pic: jtuyls.jpeg
      link: https://jens321.github.io/
      github: jens321
      scholar: https://scholar.google.com/citations?user=TPnedXMAAAAJ
      twitter: JensTuyls
      interests: ""
    hc22:
      name: Howard Chen
      title: PhD Student
      pic: hc22.png
      link: https://howard50b.github.io/
      github: howard50b
      scholar: https://scholar.google.com/citations?user=wsNa_W4AAAAJ
      twitter: __howardchen
      interests: ""
    runzhey:
      name: Runzhe Yang
      title: PhD Student
      pic: runzhey.jpeg
      link: https://runzhe-yang.science/
      github: runzheyang
      twitter: RunzheYang
      interests: ""
    shunyuy:
      name: Shunyu Yao
      title: PhD Student
      pic: shunyuy.jpeg
      link: https://ysymyth.github.io/
      github: ysymyth
      scholar: https://scholar.google.com/citations?user=qJBXk9cAAAAJ
      twitter: ShunyuYao12
      interests: ""
    murahari:
      name: Vishvak Murahari
      title: PhD Student
      pic: murahari.jpeg
      link: https://vishvakmurahari.com/
      github: vmurahari3
      scholar: https://scholar.google.com/citations?user=Y_NYX7MAAAAJ
      twitter: VishvakM
      interests: "LLMs, Efficient Inference, Distillation, "
    
    # Alumni
    jimmyyang:
      name: Jimmy Yang
      title: PhD Student
      pic: jimmyyang.jpeg
      link: https://sites.google.com/view/tyjimmyyang/home?authuser=0
      scholar: https://scholar.google.com/citations?user=g-hQdY8AAAAJ&hl=en&authuser=1
      twitter: JimmyTYYang1
      interests: "Safe Reinforcement Learning, Multi-modal representations"
      now_at: "Researcher @ Meta"
    juanduque:
      name: Juan Duque
      title: MSE Student
      pic: juanduque.jpeg
      link: https://www.linkedin.com/in/juan-duque/
      interests: "Reinforcement Learning"
      now_at: Ph.D. @ MILA
    michaelhu:
      name: Michael Hu
      title: BSE Student
      pic: https://michahu.github.io/assets/img/IMG_1080.png
      link: https://michahu.github.io/
      interests: "Representation Learning, Interpretability"
      now_at: Ph.D. @ NYU

    # Affiliates
    allenr:
      name: Allen Z. Ren
    berthyf:
      name: Berthy Feng
      pic: https://www.berthyfeng.com/images/profile.png
      link: https://www.berthyfeng.com/
    bharatg:
      name: Bharat Govil
    binghuip:
      name: Binghui Peng
    carlosc:
      name: Carlos Correa
      pic: https://carlos.correa.me/static/cgc.jpg
      link: https://carlos.correa.me/about/
    cyrilz:
      name: Cyril Zhang
      pic: https://www.microsoft.com/en-us/research/uploads/prod/2020/11/msr-cyril-headshot-1k.jpg
      link: https://cyrilzhang.com/
    felixy:
      name: Felix Yu
      pic: https://www.cs.princeton.edu/~felixy/images/felixy.jpg
      link: https://www.cs.princeton.edu/~felixy/
    hsuanp:
      name: Hsuan-Tung Peng
    ishitad:
      name: Ishita Dasgupta
      pic: https://ishita-dg.github.io/scholar_photo.jpeg
      link: https://ishita-dg.github.io/
    jacquelineh:
      name: Jacqueline He
      link: https://jacqueline-he.github.io/
    jingxiaoc:
      name: Jingxiao Chen
    justinianrosca:
      name: Justinian P. Rosca
      pic: https://i1.rgstatic.net/ii/profile.image/272903874805761-1442076762124_Q512/Justinian-Rosca.jpg
      site: https://scholar.google.com/citations?user=feURfe4AAAAJ&hl=en
    liweis:
      name: Liwei Song
    matthewh:
      name: Matthew Hausknecht
      pic: https://mhauskn.github.io/assets/img/bio-photo.jpg
      link: https://mhauskn.github.io/
    markh:
      name: Mark K. Ho
    moy:
      name: Mo Yu
    parthat:
      name: Partha Talukdar
    raeids:
      name: Raeid Saqur
      pic: https://www.cs.toronto.edu/~raeidsaqur/static/img/profile.jpg
      link: https://www.cs.toronto.edu/~raeidsaqur/
    rajam:
      name: Raja Marjieh
      pic: https://pbs.twimg.com/profile_images/1209478538795114501/42x3bs27_400x400.jpg
      link: https://psych.princeton.edu/event/raja-marjieh-phd-candidate-princeton-university-0
    roberth:
      name: Robert D. Hawkins
      pic: https://rxdhawkins.files.wordpress.com/2019/12/2efa8952-50ee-4bb5-8f5f-f3eb14752dfe_1_201_a-e1575951441133.jpeg?w=620
      link: https://rxdhawkins.com/
    rohanr:
      name: Rohan Rao
    teds:
      name: Theodore R. Sumers
      pic: https://cocosci.princeton.edu/images/ted-1.png
      link: https://www.tedsumers.info/
    sidaw:
      name: Sida I. Wang
    sreejank:
      name: Sreejan Kumar
      pic: https://pni.princeton.edu/sites/default/files/styles/people_directory/public/images/students-directory/Sreejan%20Kumar1.png?itok=Sl9H731C
      link: https://sites.google.com/site/sreejankumar97
    victorz:
      name: Victor Zhong
      pic: https://avatars.githubusercontent.com/u/1855260?v=4
      link: https://www.victorzhong.com/
    xingyuans:
      name: Xingyuan Sun
      pic: https://xingyuansun.com/images/profilepic.png
      link: https://xingyuansun.com/
    xinweiy:
      name: Xinwei Yu
    xinyic:
      name: Xinyi Chen
      pic: https://xinyi.github.io/assets/photo_1.jpg
      link: https://xinyi.github.io/
    yangz:
      name: Yang Zhang
    yilund:
      name: Yilun Du
      pic: https://yilundu.github.io/images/yilun3.png
      link: https://yilundu.github.io/
    yinlamc:
      name: Yinlam Chow
    yizhang:
      name: Yi Zhang
      pic: https://static.wixstatic.com/media/9a5322_38748aa7f9d34fe1b686d6ee90f89c4c~mv2.jpeg/v1/crop/x_0,y_0,w_1866,h_2415/fill/w_400,h_452,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/profile_photo.jpeg
      link: https://www.yi-zhang.me/
    yuwu:
      name: Yu Wu
    zeyuwang:
      name: Zeyu Wang
      pic: https://www.cs.princeton.edu/~zeyuwang/images/photo_v2.jpg
      link: https://www.cs.princeton.edu/~zeyuwang/
    zhiweid:
      name: Zhiwei Deng
      pic: https://www.cs.princeton.edu/~zhiweid/images/zhiweid.jpg
      link: https://www.cs.princeton.edu/~zhiweid/

menu:
  main:
    # NOTE: Leave all posts, may reintroduce if blog posts are created
    # - name: All Posts
    #   url: /posts
    #   weight: 4
    - name: Publications
      url: /publications
      weight: 5
    - name: People
      url: /people
      weight: 6
    - name: Join
      url: /join
      weight: 7
    - name: Tags
      url: /tags
      weight: 8
