baseURL: "http://example.org/"
languageCode: en-us
title: KLEAR
theme: lab-website-theme
favicon: favicon.ico
params:
  mode: toggle # dark mode - {toggle, auto, dark, light}
  social:
    - name: GitHub
      icon: github
      url: https://github.com/princeton-nlp
  authors:
    # Faculty
    karthikn:
      name: Karthik Narasimhan
      title: Assistant Professor
      pic: karthikn.jpeg
      link: https://www.cs.princeton.edu/~karthikn/
      github: karthikncode
      scholar: https://scholar.google.com/citations?user=euc0GX4AAAAJ
      twitter: karthik_r_n
      interests: "Embodied Language Understanding, Language Guided ML, Representation Learning, RL Safety"
    danqic:
      name: Danqi Chen
      title: Assistant Professor
      pic: danqi.jpeg
      link: https://www.cs.princeton.edu/~danqic/
    sarora:
      name: Sanjeev Arora
      title: Professor
      pic: sanjeev.jpeg
      link: https://www.cs.princeton.edu/~arora/
    olgarus:
      name: Olga Russakovsky
      title: Assistant Professor
      pic: https://www.cs.princeton.edu/~olgarus/photos/OlgaRussakovsky.JPG
      link: https://www.cs.princeton.edu/~olgarus/
    anirudhm:
      name: Anirudha Majumdar
      title: Assistant Professor
      pic: https://mae.princeton.edu/sites/default/files/Majumdar-min_1.jpg
      link: https://mae.princeton.edu/people/faculty/majumdar
    chuangg:
      name: Chuang Gan
      title: Assistant Professor
      pic: https://people.csail.mit.edu/ganchuang/imgs/portrait.jpg
      link: https://people.csail.mit.edu/ganchuang/ch
    joshuat:
      name: Joshua Tenenbaum
      title: Professor
      pic: https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRZcUwgGbxnoHdQMOqn66N8Q3QvURo2LGc5T-Pn9J2LbUaaoe3p
      link: http://web.mit.edu/cocosci/josh.html
    ramadge:
      name: Peter Ramadge
      title: Professor
      pic: https://ece.princeton.edu/sites/g/files/toruqf1836/files/styles/3x4_750w_1000h/public/ramadge-p.jpg?itok=Md1sQ0if
      link: https://ece.princeton.edu/people/peter-j-ramadge
    lukez:
      name: Luke Zettlemoyer
      title: Professor
      pic: https://s3-us-west-2.amazonaws.com/www-cse-public/images/portraits/lsz_sm.jpg
      link: https://www.cs.washington.edu/people/faculty/lsz
    christosp:
      name: Christos Papadimitriou
      title: Professor
      pic: https://ieeecs-media.computer.org/wp-media/2022/02/25182218/christos.jpg
      link: https://www.engineering.columbia.edu/faculty/christos-papadimitriou
    thomasg:
      name: Thomas L. Griffiths
      title: Professor
      pic: https://psych.princeton.edu/sites/psychology/files/styles/profile_vertical/public/faculty/tom.jpg?itok=ak4eFx-j
      link: https://psych.princeton.edu/person/tom-griffiths

    # PhD Students
    carlosej:
      name: Carlos E. Jimenez
      title: PhD Student
      pic: carlosej.jpeg
      link: http://www.carlosejimenez.com/
      github: carlosejimenez
      scholar: https://scholar.google.com/citations?user=Ue4wghAAAAAJ
      twitter: _carlosejimenez
      interests: "Efficient NLP, Multimodal Learning, Code Generation"
    jy1682:
      name: John Yang
      title: MSE Student
      pic: jy1682.jpg
      link: https://john-b-yang.github.io
      github: john-b-yang
      scholar: https://scholar.google.com/citations?user=71G11ksAAAAJ
      twitter: jyangballin
      interests: "Language Interaction, Multimodal Learning, Neurosymbolic Programs, Dialogue Systems"
    asd:
      name: Ameet Deshpande
      title: PhD Student
      pic: asd.jpg
      link: https://ameet-1997.github.io/
      github: ameet-1997
      scholar: https://scholar.google.co.in/citations?user=332L1coAAAAJ
      twitter: AmeetDeshpande_
      interests: ""
    hjwang:
      name: Austin H. Wang
      title: PhD Student
      pic: hjwang.png
      twitter: awhanjie
      link: https://ahjwang.github.io/
      github: ahjwang
      scholar: https://scholar.google.com/citations?user=BB4R2_gAAAAJ
      interests: ""
    jtuyls:
      name: Jens Tuyls
      title: PhD Student
      pic: jtuyls.jpeg
      link: https://jens321.github.io/
      github: jens321
      scholar: https://scholar.google.com/citations?user=TPnedXMAAAAJ
      twitter: JensTuyls
      interests: ""
    hc22:
      name: Howard Chen
      title: PhD Student
      pic: hc22.png
      link: https://howard50b.github.io/
      github: howard50b
      scholar: https://scholar.google.com/citations?user=wsNa_W4AAAAJ
      twitter: __howardchen
      interests: ""
    runzhey:
      name: Runzhe Yang
      title: PhD Student
      pic: runzhey.jpeg
      link: https://runzhe-yang.science/
      github: runzheyang
      twitter: RunzheYang
      interests: ""
    shunyuy:
      name: Shunyu Yao
      title: PhD Student
      pic: shunyuy.jpeg
      link: https://ysymyth.github.io/
      github: ysymyth
      scholar: https://scholar.google.com/citations?user=qJBXk9cAAAAJ
      twitter: ShunyuYao12
      interests: ""
    murahari:
      name: Vishvak Murahari
      title: PhD Student
      pic: murahari.jpeg
      link: https://vishvakmurahari.com/
      github: vmurahari3
      scholar: https://scholar.google.com/citations?user=Y_NYX7MAAAAJ
      twitter: VishvakM
      interests: ""
    
    # Alumni
    jimmyyang:
      name: Jimmy Yang
      title: PhD Student
      pic: jimmyyang.jpeg
      link: https://sites.google.com/view/tyjimmyyang/home?authuser=0
      scholar: https://scholar.google.com/citations?user=g-hQdY8AAAAJ&hl=en&authuser=1
      twitter: JimmyTYYang1
      interests: ""
    juanduque:
      name: Juan Duque
      title: MSE Student
      pic: juanduque.jpeg
      link: https://www.linkedin.com/in/juan-duque/
      interests: "Reinforcement Learning"

    # Affiliates
    allenr:
      name: Allen Z. Ren
    bharatg:
      name: Bharat Govil
    binghuip:
      name: Binghui Peng
    hsuanp:
      name: Hsuan-Tung Peng
    jacquelineh:
      name: Jacqueline He
      link: https://jacqueline-he.github.io/
    jingxiaoc:
      name: Jingxiao Chen
    justinianrosca:
      name: Justinian P. Rosca
    liweis:
      name: Liwei Song
    michaelhu:
      name: Michael Hu
      pic: https://michahu.github.io/assets/img/IMG_1080.png
      link: https://michahu.github.io/
    matthewh:
      name: Matthew Hausknecht
      pic: https://mhauskn.github.io/assets/img/bio-photo.jpg
      link: https://mhauskn.github.io/
    markh:
      name: Mark K. Ho
    moy:
      name: Mo Yu
    parthat:
      name: Partha Talukdar
    roberth:
      name: Robert D. Hawkins
    rohanr:
      name: Rohan Rao
    teds:
      name: Theodore R. Sumers
      pic: https://cocosci.princeton.edu/images/ted-1.png
      link: https://www.tedsumers.info/
    shamk:
      name: Sham Kakade
    sidaw:
      name: Sida I. Wang
    victorz:
      name: Victor Zhong
      pic: https://avatars.githubusercontent.com/u/1855260?v=4
      link: https://www.victorzhong.com/
    xinweiy:
      name: Xinwei Yu
    yangz:
      name: Yang Zhang
    yinlamc:
      name: Yinlam Chow
    yuwu:
      name: Yu Wu
    zeyuwang:
      name: Zeyu Wang
      pic: https://www.cs.princeton.edu/~zeyuwang/images/photo_v2.jpg
      link: https://www.cs.princeton.edu/~zeyuwang/

menu:
  main:
    - name: All Posts
      url: /posts
      weight: 4
    - name: Publications
      url: /publications
      weight: 5
    - name: People
      url: /people
      weight: 6
    - name: Tags
      url: /tags
      weight: 7
