baseURL: 'http://example.org/'
languageCode: en-us
title: Karthik's Language Environment and Reasoning Lab
theme: lab-website-theme
params:
  mode: toggle
  social:
    - name: GitHub
      icon: github
      url: 'https://github.com/princeton-nlp'
  authors:
    sarora:
      name: Sanjeev Arora
      link: 'https://www.cs.princeton.edu/~arora/'
      pic: 'https://princeton-nlp.github.io/assets/images/people/sanjeev-photo.jpg'
    danqic:
      name: Danqi Chen
      link: 'https://www.cs.princeton.edu/~danqic/'
      pic: 'https://princeton-nlp.github.io/assets/images/people/danqi-photo.jpg'
    karthikn:
      name: Karthik Narasimhan
      link: 'https://www.cs.princeton.edu/~karthikn/'
      pic: 'https://princeton-nlp.github.io/assets/images/people/karthik-photo.jpg'

menu:
  main:
    - name: About
      url: /about
      weight: 3
    - name: Tags
      url: /tags
      weight: 4
