baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Karthik's Language Environment and Reasoning Lab"
theme = "lab-website-theme"
[params]
	mode="toggle"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://github.com/athulcajay/"

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
