baseURL: "http://example.org/"
languageCode: en-us
title: KLEAR
theme: lab-website-theme
favicon: favicon.ico
params:
  mode: toggle # dark mode - {toggle, auto, dark, light}
  social:
    - name: GitHub
      icon: github
      url: https://github.com/princeton-nlp
  authors:
    # Faculty
    karthikn:
      name: Karthik Narasimhan
      title: Assistant Professor
      pic: karthikn.jpeg
      link: https://www.cs.princeton.edu/~karthikn/
      github: karthikncode
      scholar: https://scholar.google.com/citations?user=euc0GX4AAAAJ
      twitter: karthik_r_n
      interests: "Embodied Language Understanding, Language Guided ML, Representation Learning, RL Safety"
    anirudhm:
      name: Anirudha Majumdar
      title: Assistant Professor
      pic: anirudhm.jpeg
      link: https://mae.princeton.edu/people/faculty/majumdar
    chuangg:
      name: Chuang Gan
      title: Assistant Professor
      pic: chuangg.jpeg
      link: https://people.csail.mit.edu/ganchuang/ch
    danqic:
      name: Danqi Chen
      title: Assistant Professor
      pic: danqi.jpeg
      link: https://www.cs.princeton.edu/~danqic/
    joshuat:
      name: Joshua Tenenbaum
      title: Professor
      pic: joshuat.jpeg
      link: http://web.mit.edu/cocosci/josh.html
    olgarus:
      name: Olga Russakovsky
      title: Assistant Professor
      pic: olgarus.jpeg
      link: https://www.cs.princeton.edu/~olgarus/
    ramadge:
      name: Peter Ramadge
      title: Professor
      pic: ramadge.jpeg
      link: https://ece.princeton.edu/people/peter-j-ramadge
    sarora:
      name: Sanjeev Arora
      title: Professor
      pic: sanjeev.jpeg
      link: https://www.cs.princeton.edu/~arora/

    # PhD Students
    carlosej:
      name: Carlos E. Jimenez
      title: PhD Student
      pic: carlosej.jpeg
      link: http://www.carlosejimenez.com/
      github: carlosejimenez
      scholar: https://scholar.google.com/citations?user=Ue4wghAAAAAJ
      twitter: _carlosejimenez
      interests: "Efficient NLP, Multimodal Learning, Code Generation"
    jy1682:
      name: John Yang
      title: MSE Student
      pic: jy1682.jpg
      link: https://john-b-yang.github.io
      github: john-b-yang
      scholar: https://scholar.google.com/citations?user=71G11ksAAAAJ
      twitter: jyangballin
      interests: "Language Interaction, Multimodal Learning, Neurosymbolic Programs, Dialogue Systems"
    asd:
      name: Ameet Deshpande
      title: PhD Student
      pic: asd.jpg
      link: https://ameet-1997.github.io/
      github: ameet-1997
      scholar: https://scholar.google.co.in/citations?user=332L1coAAAAJ
      twitter: AmeetDeshpande_
      interests: ""
    hjwang:
      name: Austin H. Wang
      title: PhD Student
      pic: hjwang.png
      twitter: awhanjie
      link: https://ahjwang.github.io/
      github: ahjwang
      scholar: https://scholar.google.com/citations?user=BB4R2_gAAAAJ
      interests: ""
    jtuyls:
      name: Jens Tuyls
      title: PhD Student
      pic: jtuyls.jpeg
      link: https://jens321.github.io/
      github: jens321
      scholar: https://scholar.google.com/citations?user=TPnedXMAAAAJ
      twitter: JensTuyls
      interests: ""
    hc22:
      name: Howard Chen
      title: PhD Student
      pic: hc22.png
      link: https://howard50b.github.io/
      github: howard50b
      scholar: https://scholar.google.com/citations?user=wsNa_W4AAAAJ
      twitter: __howardchen
      interests: ""
    runzhey:
      name: Runzhe Yang
      title: PhD Student
      pic: runzhey.jpeg
      link: https://runzhe-yang.science/
      github: runzheyang
      twitter: RunzheYang
      interests: ""
    shunyuy:
      name: Shunyu Yao
      title: PhD Student
      pic: shunyuy.jpeg
      link: https://ysymyth.github.io/
      github: ysymyth
      scholar: https://scholar.google.com/citations?user=qJBXk9cAAAAJ
      twitter: ShunyuYao12
      interests: ""
    murahari:
      name: Vishvak Murahari
      title: PhD Student
      pic: murahari.jpeg
      link: https://vishvakmurahari.com/
      github: vmurahari3
      scholar: https://scholar.google.com/citations?user=Y_NYX7MAAAAJ
      twitter: VishvakM
      interests: ""
    
    # Alumni
    jimmyyang:
      name: Jimmy Yang
      title: PhD Student
      pic: jimmyyang.jpeg
      link: https://sites.google.com/view/tyjimmyyang/home?authuser=0
      scholar: https://scholar.google.com/citations?user=g-hQdY8AAAAJ&hl=en&authuser=1
      twitter: JimmyTYYang1
      interests: ""
    juanduque:
      name: Juan Duque
      title: MSE Student
      pic: juanduque.jpeg
      link: https://www.linkedin.com/in/juan-duque/
      interests: "Reinforcement Learning"

    # Affiliates
    allenr:
      name: Allen Z. Ren
    bharatg:
      name: Bharat Govil
    jacquelineh:
      name: Jacqueline He
      link: https://jacqueline-he.github.io/
    justinianrosca:
      name: Justinian P. Rosca
    moy:
      name: Mo Yu
    parthat:
      name: Partha Talukdar
    shamk:
      name: Sham Kakade
    yangz:
      name: Yang Zhang
    yuwu:
      name: Yu Wu
    zeyuwang:
      name: Zeyu Wang
      pic: zeyuwang.jpeg
      link: https://www.cs.princeton.edu/~zeyuwang/

menu:
  main:
    - name: All Posts
      url: /posts
      weight: 4
    - name: Publications
      url: /publications
      weight: 5
    - name: People
      url: /people
      weight: 6
    - name: Tags
      url: /tags
      weight: 7
